MUCodeAcademy/midland-word-game

server/config/passport.conf.js
Created a new jwt strategy that passport can utilize for user authentication.
=> creates a passport jwt strategy

src/shared/components/ProtectedRoute.jsx
Creates a protected route component so routes can be hidden behind a authentication wall.
=> creates the protect route compoent

server/routes/user.routes.js, server/shared/validate-input.js
Created User Routes for Login, Register, Verify, and Logout
NOTE: 1 Console log inside
=> creates user routes

src/shared/hooks/useAPI.jsx
creates methods in hook so client can connect to api endpoints.
=> creates use api hook for databaes connection

src/components/LoginPage.css, src/components/LoginPage.jsx
Creates a login page that should be fully functional but not tested yet.
=> creates a login page

src/index.js, src/redux/actions/wordgame.actions.js, src/redux/reducers/wordgame.reducers.js
added redux actions and reducers for game state
wrapped app in store provider in the index file
=> wordgame actions and reducers

src/index.js
=> fixed provider import from "redux" to "react-redux"

src/components/RegisterPage.jsx
Used the LoginPage styling sheet for consistency's sake. Will have to go back in and make it a more universal styling sheet later.
=> Register page

src/index.js
yeah probably important to know where the store is
=> Redux added store import in index

src/App.css, src/components/game-room/PlayerDisplay.jsx, src/components/game-room/Score.jsx
Creates a score component that renders a score board of all the players in a game.
Creates a player display component that the score component utilizes to display the filtered players in a game.
=> creates score component

server/shared/rooms.js
Here are the functions for the sockets.
=> Sockets and state (be)

src/App.css, src/components/PlayPage.jsx
Creates and styles the page and adds untested functionality.
=> creates and styles play page

src/App.js, src/components/LoginPage.jsx, src/components/word-game/WordRow.jsx, src/components/word-game/WordRowDisplay.jsx
Fixes various bugs in components so that the site can compile and run.
=> Component bug fixes

src/redux/actions/index.js, src/redux/reducers/index.js, src/redux/store.js
deletes imports for deleted code
=> Redux bugs

src/App.js, src/shared/hooks/useSocket.jsx
Fixed Issue with routing to room page
=> Router bug

server/config/socket.conf.js, server/shared/rooms.js, src/components/game-room/GamePage.jsx, src/shared/hooks/useSocket.jsx
Fixed server timer not resetting after game over.
Fixed Start round button being hidden when game is not running.
Fixed bug where it would not auto start round on game start.
Fixed nameing conventions on rooms file, useSocketHook, and socket.conf.
=> Game page bug

src/App.css, src/shared/components/Menu.jsx
Fixed the menu configuration. Will do more color theming when creating the MUI theme.
=> Refigured menu

server/config/socket.conf.js, server/shared/rooms.js, src/App.css, src/components/ClassicPage.jsx, src/components/PlayPage.jsx, src/components/game-room/GamePage.jsx, src/components/word-game/WordBoard.jsx, src/components/word-game/WordRow.jsx, src/shared/hooks/useSocket.jsx
Creates and edits functions to make single player functionality possible.
=> creates single player game functionality

src/App.css, src/components/game-room/Clock.jsx, src/components/game-room/GamePage.jsx, src/components/game-room/PlayerDisplay.jsx, src/components/game-room/Score.jsx, src/shared/hooks/useSocket.jsx
Re styles the score component.
Moves the timer out to clock component.
=> Score board restyle

src/components/word-game/WordBoard.jsx
Creates functions for letter coloring base on if they are correct wrong or misplaced in the current round word.
=> creates logic for letter coloring

src/components/ClassicPage.jsx
Fixes buttons on classic page to be mui buttons.
=> Classic fix

src/shared/components/Menu.jsx
Fixes logout button to logout the user.
Makes the sidebar close on a link click.
=> fixes logout button

server/config/socket.conf.js, src/App.css, src/components/PlayPage.jsx, src/shared/hooks/useSocket.jsx
Creates a way to check if it is a valid room before joining.
=> implements a room check before joining

src/components/ClassicPage.jsx, src/components/word-game/WordBoard.jsx
Fixes word board so so that the classic version displays correct.
Makes classic page more line with game page styling.
=> fixes classic page

src/App.css, src/components/word-game/WordKeyboard.jsx
adds brand-specific orange to keyboard and removes unused items
=> Word keyboard tweaks

src/App.css
changes coloring of guessed letters
=> fixes coloring for guessed letters

src/components/ClassicPage.jsx, src/components/word-game/WordRow.jsx, src/shared/hooks/useSocket.jsx
Fixes styling for classic page.
Fixes bug where invalid word error still appeared after typing a valid word.
=> Classic style fix

src/components/word-game/WordRow.jsx
Moves were the user sees their input on classic page.
=> changes where player inputs text on classic
